<?php

function mw_avatar_lore_dataset(): array {
    return [
        'albert-einstein' => [
            'class_label' => 'Strategist',
            'role' => 'Control and energy advantage',
            'culture' => 'Modern Science',
            'description' => 'Albert Einstein was a theoretical physicist who transformed our understanding of the universe with the theory of relativity. His strategic mind and ability to anticipate consequences make him a fighter who controls the pace of battle.',
            'short_lore' => 'Einstein revolutionized physics with the theory of relativity.',
        ],
        'benjamin-franklin' => [
            'class_label' => 'Strategist',
            'role' => 'Energy and tactical control',
            'culture' => 'Enlightenment / American History',
            'description' => 'Benjamin Franklin was a visionary scientist, inventor, and statesman. His command of electricity and strategic thinking allow him to turn knowledge into power in the middle of battle.',
        ],
        'sherlock-holmes' => [
            'class_label' => 'Controller',
            'role' => 'Weaken enemies and manipulate combat',
            'culture' => 'Literature / Victorian England',
            'description' => 'Sherlock Holmes is London\'s greatest detective. His ability to analyze patterns and predict movements lets him exploit weaknesses and control the flow of combat.',
        ],
        'wukong' => [
            'class_label' => 'Trickster',
            'role' => 'Mobility, deception, and unpredictable attacks',
            'culture' => 'Chinese Mythology',
            'description' => 'Sun Wukong, the Monkey King, is a legendary warrior known for his cunning and supernatural abilities. A master of deception and transformation, he confuses his enemies while unleashing unexpected attacks.',
        ],
        'sun-wukong' => [
            'class_label' => 'Trickster',
            'role' => 'Mobility, deception, and unpredictable attacks',
            'culture' => 'Chinese Mythology',
            'description' => 'Sun Wukong, the Monkey King, is a legendary warrior known for his cunning and supernatural abilities. A master of deception and transformation, he confuses his enemies while unleashing unexpected attacks.',
        ],
        'zeus' => [
            'class_label' => 'Striker',
            'role' => 'Explosive damage and combat control',
            'culture' => 'Greek Mythology',
            'description' => 'Zeus is the king of the Olympian gods and lord of thunder. With absolute power over the skies, he unleashes devastating attacks that can change the course of battle in seconds.',
        ],
        'medusa' => [
            'class_label' => 'Controller',
            'role' => 'Status control and weakening',
            'culture' => 'Greek Mythology',
            'description' => 'Medusa was once a mortal woman, transformed into a monstrous creature by the gods. Her petrifying gaze can stop any enemy, making her a constant threat on the battlefield.',
        ],
        'kraken' => [
            'class_label' => 'Tank',
            'role' => 'Extreme durability and constant pressure',
            'culture' => 'Norse / Maritime Mythology',
            'description' => 'The Kraken is a gigantic sea creature feared by sailors for centuries. Its colossal strength and durability make it an enemy that is almost impossible to bring down.',
        ],
        'jack-frost' => [
            'class_label' => 'Controller',
            'role' => 'Freeze effects and speed control',
            'culture' => 'European Folklore',
            'description' => 'Jack Frost is the spirit of winter who brings ice and frost. His powers freeze the battlefield, slowing enemies and dominating the pace of combat.',
        ],
        'alice' => [
            'class_label' => 'Trickster',
            'role' => 'Unpredictable chaos and random effects',
            'culture' => 'Literature / Wonderland',
            'description' => 'Alice is a traveler from a world full of absurdity and wonder. Her unpredictable nature introduces chaos into combat, creating unexpected situations that can benefit either side.',
        ],
        'thor' => [
            'class_label' => 'Striker',
            'role' => 'Heavy damage and offensive pressure',
            'culture' => 'Norse Mythology',
            'description' => 'Thor is the god of thunder and protector of Asgard. Armed with his hammer Mjolnir, he unleashes devastating attacks capable of bringing down even the toughest enemies.',
        ],
        'odin' => [
            'class_label' => 'Strategist',
            'role' => 'Tactical control and battlefield vision',
            'culture' => 'Norse Mythology',
            'description' => 'Odin, the All-Father, is a god of wisdom and strategy. His knowledge of fate and the battlefield allows him to manipulate combat in his favor.',
        ],
        'dracula' => [
            'class_label' => 'Trickster',
            'role' => 'Life steal and enemy attrition',
            'culture' => 'Gothic Literature / European Folklore',
            'description' => 'Dracula is the legendary vampire who feeds on the life of his enemies. His dark presence and regenerative power make him a dangerous opponent.',
        ],
        'isaac-newton' => [
            'class_label' => 'Strategist',
            'role' => 'Precision control and calculation',
            'culture' => 'Scientific Revolution',
            'description' => 'Isaac Newton was one of the most influential scientists in history. His understanding of motion and gravity allows him to predict and control the flow of combat.',
        ],
        'athena' => [
            'class_label' => 'Controller',
            'role' => 'Strategic defense and field control',
            'culture' => 'Greek Mythology',
            'description' => 'Athena is the goddess of wisdom and strategic warfare. She favors intelligence over brute force, guiding combat with discipline and precision.',
        ],
        'anubis' => [
            'class_label' => 'Controller',
            'role' => 'Debilitation and psychological pressure',
            'culture' => 'Egyptian Mythology',
            'description' => 'Anubis is the guardian of the afterlife and judge of souls. His presence on the battlefield weakens enemies and controls the balance between life and death.',
        ],
        'nikola-tesla' => [
            'class_label' => 'Strategist',
            'role' => 'Energy and technological control',
            'culture' => 'Modern Science',
            'description' => 'Nikola Tesla was a visionary inventor who imagined a world powered by electricity. His revolutionary ideas translate into energy attacks and battlefield manipulation.',
        ],
        'robin-hood' => [
            'class_label' => 'Trickster',
            'role' => 'Mobility and opportunistic attacks',
            'culture' => 'English Folklore',
            'description' => 'Robin Hood is the legendary archer who steals from the rich to help the poor. Fast and cunning, he strikes from the shadows before his enemies can react.',
        ],
        'joan-of-arc' => [
            'class_label' => 'Tank',
            'role' => 'Durability and defensive leadership',
            'culture' => 'European History',
            'description' => 'Joan of Arc was a heroine who led armies with faith and determination. In combat, her unbreakable will turns her into a wall that is hard to break.',
        ],
        'hercules' => [
            'class_label' => 'Tank',
            'role' => 'Brute force and extreme durability',
            'culture' => 'Greek Mythology',
            'description' => 'Hercules is the legendary hero known for his twelve impossible labors. His superhuman strength and endurance make him one of the most formidable fighters.',
        ],
        'abraham-lincoln' => [
            'class_label' => 'Strategist',
            'role' => 'Leadership and conflict strategy',
            'culture' => 'American History',
            'description' => 'The 16th President of the United States, Abraham Lincoln led his nation through one of its darkest periods. Known for his determination and wisdom, he represents leadership, resilience, and strategic thinking in the face of conflict.',
        ],
        'aladdin' => [
            'class_label' => 'Trickster',
            'role' => 'Wit, agility, and unpredictable tactics',
            'culture' => 'Middle Eastern Folklore',
            'description' => 'A clever street survivor who discovered a magical lamp, Aladdin relies on wit, agility, and unexpected tricks to overcome stronger opponents.',
        ],
        'arthur-king' => [
            'class_label' => 'Tank',
            'role' => 'Defensive leadership and frontline resilience',
            'culture' => 'Arthurian Legend',
            'description' => 'The legendary king of Camelot and wielder of Excalibur. Arthur stands as a symbol of honor and unbreakable resolve, defending allies with unwavering strength.',
        ],
        'king-arthur' => [
            'class_label' => 'Tank',
            'role' => 'Defensive leadership and frontline resilience',
            'culture' => 'Arthurian Legend',
            'description' => 'The legendary king of Camelot and wielder of Excalibur. Arthur stands as a symbol of honor and unbreakable resolve, defending allies with unwavering strength.',
        ],
        'corrupted-loki' => [
            'class_label' => 'Trickster',
            'role' => 'Chaos, deception, and dark magic pressure',
            'culture' => 'Norse Mythology',
            'description' => 'A twisted version of the infamous trickster god. Corrupted Loki thrives on chaos, deception, and dark magic, turning the battlefield into unpredictable madness.',
        ],
        'corrupted-odin' => [
            'class_label' => 'Controller',
            'role' => 'Supernatural control and oppressive manipulation',
            'culture' => 'Norse Mythology',
            'description' => 'A fallen All-Father consumed by forbidden knowledge. Corrupted Odin manipulates the battlefield with ominous wisdom and overwhelming supernatural control.',
        ],
        'dorian-gray' => [
            'class_label' => 'Trickster',
            'role' => 'Manipulation and psychological deception',
            'culture' => 'Gothic Literature',
            'description' => 'A man whose portrait bears the weight of his sins while he remains eternally young. Dorian Gray thrives on manipulation, vanity, and psychological deception.',
        ],
        'fenrir' => [
            'class_label' => 'Striker',
            'role' => 'Savage burst damage and relentless aggression',
            'culture' => 'Norse Mythology',
            'description' => 'The monstrous wolf destined to bring destruction during Ragnarok. Fenrir attacks with savage power and unstoppable ferocity.',
        ],
        'frankenstein' => [
            'class_label' => 'Tank',
            'role' => 'Massive durability and sustained pressure',
            'culture' => 'Gothic Literature',
            'description' => 'A creature brought to life through forbidden science. Frankenstein\'s immense strength and resilience make him nearly impossible to bring down.',
        ],
        'genghis-khan' => [
            'class_label' => 'Strategist',
            'role' => 'Relentless strategy and battlefield domination',
            'culture' => 'Mongol Empire History',
            'description' => 'Founder of the Mongol Empire and one of history\'s greatest conquerors. Genghis Khan dominates battles through relentless strategy and overwhelming force.',
        ],
        'george-washington' => [
            'class_label' => 'Strategist',
            'role' => 'Discipline, command, and tactical leadership',
            'culture' => 'American History',
            'description' => 'The first President of the United States and a revolutionary leader. Washington excels in discipline, strategy, and battlefield leadership.',
        ],
        'headless-horseman' => [
            'class_label' => 'Striker',
            'role' => 'High-speed offense and fear pressure',
            'culture' => 'American Folklore',
            'description' => 'A spectral rider who haunts the night without a head. The Headless Horseman charges into battle with terrifying speed and unstoppable force.',
        ],
        'hydra' => [
            'class_label' => 'Tank',
            'role' => 'Regeneration and persistent frontline pressure',
            'culture' => 'Greek Mythology',
            'description' => 'A terrifying multi-headed serpent that grows stronger with every attack. Hydra\'s regenerative nature makes it a persistent and dangerous opponent.',
        ],
        'ichabod-crane' => [
            'class_label' => 'Strategist',
            'role' => 'Cautious tactics and adaptive intelligence',
            'culture' => 'American Folklore',
            'description' => 'The superstitious schoolmaster of Sleepy Hollow. Though easily frightened, his keen mind helps him navigate the strange and mysterious.',
        ],
        'julius-caesar' => [
            'class_label' => 'Strategist',
            'role' => 'Tactical brilliance and command presence',
            'culture' => 'Roman History',
            'description' => 'One of Rome\'s greatest generals and political leaders. Caesar commands battles through tactical brilliance and unwavering ambition.',
        ],
        'julio-cesar' => [
            'class_label' => 'Strategist',
            'role' => 'Tactical brilliance and command presence',
            'culture' => 'Roman History',
            'description' => 'One of Rome\'s greatest generals and political leaders. Caesar commands battles through tactical brilliance and unwavering ambition.',
        ],
        'krampus' => [
            'class_label' => 'Controller',
            'role' => 'Fear control and chaos pressure',
            'culture' => 'Alpine Folklore',
            'description' => 'A terrifying creature that punishes the wicked during winter nights. Krampus spreads fear and chaos wherever he appears.',
        ],
        'little-red-riding-hood' => [
            'class_label' => 'Striker',
            'role' => 'Brave offense and opportunistic strikes',
            'culture' => 'European Fairy Tales',
            'description' => 'A brave girl who ventured through dangerous forests and faced the legendary wolf. Beneath her innocent appearance lies surprising courage.',
        ],
        'long-john-silver' => [
            'class_label' => 'Strategist',
            'role' => 'Cunning planning and ruthless opportunism',
            'culture' => 'Pirate Literature',
            'description' => 'The cunning pirate from Treasure Island. Long John Silver survives through clever strategy and ruthless opportunism.',
        ],
        'mad-hatter' => [
            'class_label' => 'Trickster',
            'role' => 'Unpredictability and disruptive confusion',
            'culture' => 'Wonderland Literature',
            'description' => 'A bizarre tea-party host whose mind operates in delightful chaos. The Mad Hatter confuses enemies with unpredictable actions.',
        ],
        'morgana' => [
            'class_label' => 'Controller',
            'role' => 'Dark magic control and battlefield manipulation',
            'culture' => 'Arthurian Legend',
            'description' => 'A powerful sorceress often seen as the rival of King Arthur. Morgana bends dark magic to control the battlefield.',
        ],
        'napoleon-bonaparte' => [
            'class_label' => 'Strategist',
            'role' => 'Discipline, planning, and command efficiency',
            'culture' => 'European History',
            'description' => 'One of history\'s most brilliant military commanders. Napoleon wins battles through discipline, planning, and relentless ambition.',
        ],
        'pinocchio' => [
            'class_label' => 'Trickster',
            'role' => 'Mischief-driven unpredictability and adaptation',
            'culture' => 'Italian Fairy Tale',
            'description' => 'A wooden puppet who dreamed of becoming a real boy. Pinocchio\'s mischievous nature leads to surprising and unpredictable outcomes.',
        ],
        'puss-in-boots' => [
            'class_label' => 'Trickster',
            'role' => 'Charm, cunning schemes, and confident plays',
            'culture' => 'European Fairy Tale',
            'description' => 'A clever cat who turned wit and charm into power. Puss in Boots wins battles through cunning schemes and bold confidence.',
        ],
        'pussy-in-boots' => [
            'class_label' => 'Trickster',
            'role' => 'Charm, cunning schemes, and confident plays',
            'culture' => 'European Fairy Tale',
            'description' => 'A clever cat who turned wit and charm into power. Puss in Boots wins battles through cunning schemes and bold confidence.',
        ],
        'queen-grimhilde' => [
            'class_label' => 'Controller',
            'role' => 'Sinister magic and manipulative control',
            'culture' => 'European Fairy Tale',
            'description' => 'The dark queen obsessed with beauty and power. Grimhilde commands sinister magic and manipulates those around her.',
        ],
        'rapunzel' => [
            'class_label' => 'Strategist',
            'role' => 'Clarity, resilience, and tactical balance',
            'culture' => 'European Fairy Tale',
            'description' => 'A princess raised in isolation whose strength comes from resilience and hope. Rapunzel brings clarity and balance to chaotic situations.',
        ],
        'sandman' => [
            'class_label' => 'Controller',
            'role' => 'Dream control and reality disruption',
            'culture' => 'European Folklore',
            'description' => 'The mystical bringer of dreams who governs the realm of sleep. Sandman bends the line between reality and illusion.',
        ],
        'simon-bolivar' => [
            'class_label' => 'Strategist',
            'role' => 'Visionary leadership and revolutionary resolve',
            'culture' => 'Latin American History',
            'description' => 'A revolutionary leader who fought for the independence of several nations. Bolivar represents determination, vision, and fearless leadership.',
        ],
        'wendigo' => [
            'class_label' => 'Striker',
            'role' => 'Primal ferocity and relentless aggression',
            'culture' => 'Native American Folklore',
            'description' => 'A terrifying spirit associated with endless hunger and winter. The Wendigo embodies raw ferocity and primal rage.',
        ],
        // Updated epic definitions for shared characters.
        'anubis' => [
            'class_label' => 'Controller',
            'role' => 'Ancient debilitation and life-death control',
            'culture' => 'Egyptian Mythology',
            'description' => 'Guardian of the afterlife and judge of souls, Anubis commands ancient powers that weaken enemies and control the balance between life and death.',
        ],
        'dracula' => [
            'class_label' => 'Trickster',
            'role' => 'Dark deception and relentless survival',
            'culture' => 'European Gothic Folklore',
            'description' => 'The legendary vampire lord who feeds on the life force of his enemies. Dracula is a master of darkness, deception, and relentless survival.',
        ],
        'hercules' => [
            'class_label' => 'Tank',
            'role' => 'Unmatched strength and heroic endurance',
            'culture' => 'Greek Mythology',
            'description' => 'A legendary hero known for completing twelve impossible labors. Hercules possesses unmatched strength and heroic endurance.',
        ],
        'isaac-newton' => [
            'class_label' => 'Strategist',
            'role' => 'Calculated precision and intellectual dominance',
            'culture' => 'Scientific Revolution',
            'description' => 'A brilliant scientist who uncovered the laws of motion and gravity. Newton approaches combat with calculated precision and intellectual dominance.',
        ],
        'loki' => [
            'class_label' => 'Trickster',
            'role' => 'Cunning illusions and unpredictable schemes',
            'culture' => 'Norse Mythology',
            'description' => 'The original god of mischief. Loki manipulates events with cunning illusions and unpredictable schemes.',
        ],
        'odin' => [
            'class_label' => 'Strategist',
            'role' => 'Wisdom-driven control and strategic foresight',
            'culture' => 'Norse Mythology',
            'description' => 'The All-Father and seeker of wisdom. Odin sacrifices everything in pursuit of knowledge and ultimate power.',
        ],
        'thor' => [
            'class_label' => 'Striker',
            'role' => 'Immense power and unstoppable offense',
            'culture' => 'Norse Mythology',
            'description' => 'God of thunder and protector of the realms. Thor strikes with immense power and unstoppable force.',
        ],
        'zeus' => [
            'class_label' => 'Striker',
            'role' => 'Divine lightning control and battlefield dominance',
            'culture' => 'Greek Mythology',
            'description' => 'King of the Olympian gods and master of lightning. Zeus commands divine power capable of reshaping the battlefield.',
        ],
    ];
}

